### ISSUE TITLE
Add support of Ubuntu 17.04 / Linux kernel 4.10

### ISSUE THREAD

**Issue by green2k** [ivannieto/archer-t2u-ubuntu-installer#5]
It would be super-cool, if the Ubuntu 17.04 / Linux kernel 4.10 would be supported!

**Comment by ivannieto** [comment]
This was made for personal use, but indeed I'll check it through this days from now on.

Thanks for the call!

**Comment by positiveday** [comment]
Hello, I've just installed on Mint Cinnamon 64 bit, kernel 4.10.0-32 on Intel and it works perfect.
The only note is the file name that is wrong in the "code" page example 
"cd archer-t2u-ubuntu-installer/ && python3 t2u-installer.py" is wrong
the right file name is 
"cd archer-t2u-ubuntu-installer/ && python3 t2u-driver-installer.py"
Many thanks for your work.

**Comment by ivannieto** [comment]
Thanks about the feedback @positiveday, it's now fixed.

**Comment by ivannieto** [comment]
Fixed for 17.10 from #7 

Can anyone check if the current status works for 17.04 as well?

**Comment by JosefRypacek** [comment]
Hi, I'm using 17.04, but I can't get the driver working... 
Instalation and 'sudo t2u-driver' works fine, but it does not work at all...  I found that I'm still getting dmesg messages like below until t2u-driver disable. Can you give me any hint? 
Thanks

[ 4277.037011] #
[ 4277.254573] RTMP_TimerListAdd: add timer obj ffffbbe8c375a1e0!
[ 4277.254575] RTMP_TimerListAdd: add timer obj ffffbbe8c375a250!
[ 4277.254575] RTMP_TimerListAdd: add timer obj ffffbbe8c375a2c0!
[ 4277.254576] RTMP_TimerListAdd: add timer obj ffffbbe8c375a170!
[ 4277.254577] RTMP_TimerListAdd: add timer obj ffffbbe8c375a020!
[ 4277.254578] RTMP_TimerListAdd: add timer obj ffffbbe8c375a090!
[ 4277.254579] RTMP_TimerListAdd: add timer obj ffffbbe8c36ecd18!
[ 4277.254580] RTMP_TimerListAdd: add timer obj ffffbbe8c36dbb80!
[ 4277.254580] RTMP_TimerListAdd: add timer obj ffffbbe8c36dbbf8!
[ 4277.254581] RTMP_TimerListAdd: add timer obj ffffbbe8c36ece88!
[ 4277.254582] RTMP_TimerListAdd: add timer obj ffffbbe8c36ecc38!
[ 4277.254583] RTMP_TimerListAdd: add timer obj ffffbbe8c36ece18!
[ 4277.254634] cfg_mode=5
[ 4277.254635] wmode_band_equal(): Band Not Equal!
[ 4277.254739] Key1Str is Invalid key length(0) or Type(0)
[ 4277.254749] Key2Str is Invalid key length(0) or Type(0)
[ 4277.254760] Key3Str is Invalid key length(0) or Type(0)
[ 4277.254770] Key4Str is Invalid key length(0) or Type(0)
[ 4277.254991] 1. Phy Mode = 31
[ 4277.254992] 2. Phy Mode = 31
[ 4277.254993] NVM is Efuse and its size =1d[1e0-1fc] 
[ 4277.265938] /home/...../archer-t2u-ubuntu-installer/driver-files/os/linux/../../chips/mt76x0.c:2114 assert (pAd->TxPower[choffset].Channel == 36)failed
[ 4277.277057] ERROR!!! 
[ 4277.277062] E2PROM: WRONG VERSION 0x2, should be 1
[ 4277.281437] mt76x0_read_tx_alc_info_from_eeprom: EEPROM_MT76x0_TEMPERATURE_OFFSET (0xD1) = 0xf8
[ 4277.281457] mt76x0_read_tx_alc_info_from_eeprom: TemperatureOffset = 0xfffffff8
[ 4277.281458] Temperature Tx ALC not enabled
[ 4277.297727] 3. Phy Mode = 31
[ 4277.297731] AntCfgInit: primary/secondary ant 0/1
[ 4277.303444] RTMPSetPhyMode: channel is out of range, use first channel=1 
[ 4277.304805] MCS Set = ff 00 00 00 01
[ 4277.314858] <==== rt28xx_init, Status=0
[ 4277.316311] 0x1300 = 00064300
[ 4277.316313] RTMPDrvSTAOpen(1):Check if PDMA is idle!
[ 4277.316442] RTMPDrvSTAOpen(2):Check if PDMA is idle!
[ 4277.355574] ==>RT65xx_WLAN_ChipOnOff(): OnOff:0, Reset= 0, pAd->WlanFunCtrl:0xff000003, Reg-WlanFunCtrl=0xff000003
[ 4277.371377] ERROR!!! 
[ 4277.371380] RTMPSetTimer failed, Halt in Progress!
[ 4277.373679] receive cmd msg fail(-2)
[ 4277.373770] tx_kickout_fail_count = 0
[ 4277.373770] tx_timeout_fail_count = 0
[ 4277.373771] rx_receive_fail_count = 0
[ 4277.373772] alloc_cmd_msg = 245
[ 4277.373772] free_cmd_msg = 245
[ 4277.429677] ==>RT65xx_WLAN_ChipOnOff(): OnOff:1, Reset= 0, pAd->WlanFunCtrl:0xff000000, Reg-WlanFunCtrl=0xff000000
[ 4277.435800] -->RTUSBVenderReset
[ 4277.435921] <--RTUSBVenderReset
[ 4277.440883] fw version:0.1.00 
[ 4277.440884] build:7640
[ 4277.440885] build time:
[ 4277.440885] 2
[ 4277.440885] 0
[ 4277.440886] 1
[ 4277.440886] 3
[ 4277.440886] 0
[ 4277.440886] 8
[ 4277.440887] 2
[ 4277.440887] 2
[ 4277.440887] 1
[ 4277.440888] 6
[ 4277.440888] 5
[ 4277.440888] 5
[ 4277.440888] _
[ 4277.440889] _
[ 4277.440889] _
[ 4277.440889] _

**Comment by ivannieto** [comment]
Sorry, but I will not provide support for any other version until LTS 18.04.

Can't find the time to work on this actually, so if anyone is interested, please, send a PR and I'll be glad to merge it.

My apologies.

**Comment by JosefRypacek** [comment]
I understand...  
Which version is currently supported? Depends on Ubuntu version or kernel version?

I know nothing about drivers so I can't send PR...

**Comment by kaszperro** [comment]
@JosefRypacek With my pull request (https://github.com/ivannieto/archer-t2u-ubuntu-installer/pull/7) I've added support for ubuntu 17.10, it works on my PC fine with no errors. I'd rather you upgraded to ubuntu 17.10.
Regards

**Comment by JosefRypacek** [comment]
I've upgraded to 17.10 (I hope my notebook will survive) and this driver works like a charm. 
Thank you!

**Comment by ivannieto** [comment]
I will close this issue for now. Thanks a lot @kaszperro ❤️

**Comment by aneek** [comment]
@ivannieto since Ubuntu 18.04 is out and I have this dongle which doesn't work on 18.04, could you please share the roadmap when a latest version would be out? (or you are not maintaining this now?)
